services:
  app_who_etl:
    pull_policy: build
    image: app_who_etl:latest
    volumes:
      - .:/app_who_etl
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 5678:5678
    depends_on:
      app_who_etl_postgres_service:
        condition: service_healthy
    # This adds debugpy to the environment so you can debug the app
    entrypoint: [ "sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run" ]
    environment:
      - FLASK_APP=src/app_who_etl/app.py
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PORT=${PORT}
    env_file:
      - .env
  app_who_etl_postgres_service:
    extends:
      file: docker-compose-common.yml
      service: app_who_etl_postgres_service
