FROM mcr.microsoft.com/devcontainers/python:3.13

EXPOSE 8080

WORKDIR /app_who_etl

ENV PYTHONUNBUFFERED=1

COPY . .

RUN pipenv sync --system -d

RUN apt-get update \
    && apt-get install aspell -y

RUN adduser -u 5678 --disabled-password --gecos "" app_who_etl && chown -R app_who_etl /app_who_etl
USER app_who_etl

RUN chmod +x ./entrypoint.dev.sh

ENTRYPOINT [ "./entrypoint.dev.sh" ]
